name: Java CI

on: [push, pull_request]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')" 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Skript
      run: ./gradlew clean build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Skript
        path: build/libs/Skript.jar
